name: ci-node
on: 
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repositort 
        uses: actions/checkout@v4

      - name: Configura o node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instala dependencias
        run: npm ci

      - name: Executa testes
        run: npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
